CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20),
    role VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS course (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS lecture (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    course_id BIGINT,
    FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    timestamp TIMESTAMP,
    lecture_id BIGINT,
    FOREIGN KEY (lecture_id) REFERENCES lecture(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS course_material (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(100),
    lecture_id BIGINT NOT NULL,
    data LONGBLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS poll (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    end_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS poll_option (
    poll_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    option_text VARCHAR(255) NOT NULL,
    vote_count INT DEFAULT 0,
    PRIMARY KEY (poll_id, option_id),
    FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE
);




CREATE TABLE IF NOT EXISTS poll_comment (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,
poll_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
content TEXT NOT NULL,
                                                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                                FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE,
                                                FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_poll_vote (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
                                              user_id BIGINT NOT NULL,
                                              poll_id BIGINT NOT NULL,
                                              option_id BIGINT NOT NULL,
                                              voted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                              FOREIGN KEY (poll_id) REFERENCES poll(id) ON DELETE CASCADE,
                                              FOREIGN KEY (poll_id, option_id) REFERENCES poll_option(poll_id, option_id) ON DELETE CASCADE
);



